
SELECT DEPT_CODE, SUM(SALARY) 합계, FLOOR(AVG(SALARY))평균, COUNT(*)인원수
FROM EMPLOYEE
HAVING FLOOR(AVG(SALARY)) > 2800000
GROUP BY DEPT_CODE
ORDER BY DEPT_CODE ASC;

SELECT ROWNUM, EMP_NAME, SALARY
FROM EMPLOYEE
WHERE ROWNUM <= 3
ORDER BY SALARY DESC;


SELECT ROWNUM, S.*
FROM (SELECT ENAME, SAL
        FROM EMP
        WHERE ROWNUM <=3
        ORDER BY SAL DESC) S
ORDER BY ROWNUM ASC;